# Generated by Django 4.2.23 on 2025-06-27 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Websites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'websites',
            },
        ),
        migrations.CreateModel(
            name='NewsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.TextField()),
                ('article_url', models.TextField()),
                ('image_url', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('published_time', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tamil_news.websites')),
            ],
            options={
                'db_table': 'news_details',
            },
        ),
        migrations.AddConstraint(
            model_name='newsdetails',
            constraint=models.UniqueConstraint(fields=('website', 'category', 'article_url'), name='unique_website_category_url'),
        ),
    ]
