# Generated by Django 4.2.23 on 2025-07-10 11:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tamil_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_label', models.CharField(max_length=50)),
                ('sentiment_score', models.FloatField()),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='tamil_news.newsdetails')),
            ],
            options={
                'db_table': 'sentiment_results',
            },
        ),
    ]
