# Generated by Django 4.2.23 on 2025-07-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamil_news', '0002_sentimentresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentresults',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sentimentresults',
            name='website_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
