# Generated by Django 4.2.23 on 2025-07-28 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tamil_news', '0003_sentimentresults_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'keywords',
            },
        ),
        migrations.AddField(
            model_name='sentimentresults',
            name='negative_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentimentresults',
            name='neutral_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentimentresults',
            name='positive_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentimentresults',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentimentresults',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tamil_news.newsdetails'),
        ),
        migrations.AddField(
            model_name='newsdetails',
            name='keywords',
            field=models.ManyToManyField(related_name='news', to='tamil_news.keyword'),
        ),
        migrations.AddField(
            model_name='sentimentresults',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tamil_news.keyword'),
        ),
    ]
