# Generated by Django 4.2.23 on 2025-07-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamil_news', '0004_keyword_sentimentresults_negative_score_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sentimentresults',
            constraint=models.UniqueConstraint(fields=('news', 'keyword'), name='unique_news_keyword'),
        ),
    ]
